apiVersion: v1
kind: Service
metadata:
  name: nodeauthentication
spec:
  selector:
    app: nodeauthentication
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeauthentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeauthentication
  template:
    metadata:
      labels:
        app: nodeauthentication
    spec:
      containers:
        - name: nodeauthentication
          image: 1000006652/nodeauth
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always
