apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
    role: master
    tier: backend
spec:
  ports:
    - port: 27017
      targetPort: 27017
  # Replace with the IP of your minikube node / master node if you want external access
#   externalIPs:
#     - 127.0.0.1:32768
  selector:
    app: mongo
    role: master
    tier: backend